Added Project Euler
Rishit-dagli/Python3-by-practice pull request #49
Opened 2020-10-03 15:10 UTC by shubhamsah

Added a folder named Project Euler that contains solutions to Project Euler Problems

2020-10-04 14:28 UTC, Rishit-dagli requested changes
I am still performing a content review on this, but what is your take about having the following directory structure instead-

```
Project Euler
├── Problem 1
|   └── README.md (The problem statement)
|   └── solution1.py
|   └── solution2.py
├── Problem 2
|   └── README.md (The problem statement)
|   └── solution1.py
|   └── solution2.py
├── Problem ...
└── README.md (A bit about Project Euler)
```

2020-10-04 14:28 UTC, Rishit-dagli commented on Project Euler/problem_01/sol1.py
> +"""
Not a huge edit but I see you have been following a consistent style, could you remove the double `"""`

2020-10-04 14:30 UTC, shubhamsah commented
Alright, will do the necessary changes

2020-10-04 21:31 UTC, shubhamsah commented
All the necessary changes requested has been done

2020-10-05 02:42 UTC, Rishit-dagli approved these changes
This looks good to me, I will go ahead and merge this. I have also made minor edits in README styling via [`502bde0`](https://github.com/Rishit-dagli/Python3-by-practice/pull/49/commits/502bde0a0ecec27515d1d89915e5134fb81e1415) and [`a995fd3`](https://github.com/Rishit-dagli/Python3-by-practice/pull/49/commits/a995fd330fd85ffaf8e5715d07c66214d4cc4fbe). Thank you for your contribution 💯 Feel free to support this repo by leaving a ⭐ !

2020-10-05 02:43 UTC, merged

2020-10-05 04:39 UTC, Rishit-dagli commented
@all-contributors please add @shubhamsah for code