Project Euler Problem 06
Rishit-dagli/Python3-by-practice pull request #86
Opened 2020-10-08 12:52 UTC by theja-vanka

2020-10-08 12:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Rishit-dagli/Python3-by-practice?pullRequest=86) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Rishit-dagli/Python3-by-practice?pullRequest=86) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Rishit-dagli/Python3-by-practice?pullRequest=86) it.</sub>

2020-10-08 13:00 UTC, Rishit-dagli commented
@theja-vanka Could you sign the CLA mentioned in [this comment](https://github.com/Rishit-dagli/Python3-by-practice/pull/86#issuecomment-705546825) to move forward with this PR.

2020-10-08 13:03 UTC, theja-vanka commented
Hey done. Let me know if I have anything else that I may have to comply with.

2020-10-08 13:14 UTC, Rishit-dagli requested changes

2020-10-08 13:14 UTC, Rishit-dagli commented on Project Euler/problem_06/README.md
> +The sum of the squares of the first ten natural numbers is,
To maintain consistency could you add 

```
### Problem Statement :
```

at the start.

2020-10-08 13:14 UTC, Rishit-dagli commented on Project Euler/problem_06/README.md
> +Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.
Are there any sample test cases, available if yes please add them

2020-10-08 13:21 UTC, theja-vanka commented
Please Check now.

2020-10-08 13:23 UTC, Rishit-dagli approved these changes
This looks good to me, I will go ahead and merge it. Thank you for your contribution 💯 Feel free to support this repo by leaving a :star: !

2020-10-08 13:24 UTC, merged

2020-10-08 13:24 UTC, theja-vanka commented
Thank you very much !! Enjoyed the privilage to contribute.

2020-10-13 03:28 UTC, Rishit-dagli commented
@all-contributors please add @theja-vanka for code